apiVersion: v1
kind: ConfigMap
metadata:
  name: fast-food-config
data:
  DB_HOST: "https://fastfood-terraform-state.s3.us-east-1.amazonaws.com/db/terraform.tfstate"  # << endpoint real do RDS
  DB_PORT: "5432"
  DB_NAME: "fastfood"
  ALGORITHM: "HS256"
  ACCESS_TOKEN_EXPIRE_MINUTES: "30"
