apiVersion: batch/v1
kind: Job
metadata:
  name: run-migrations
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: 039539140324.dkr.ecr.us-east-1.amazonaws.com/fastfood-app:latest
          command: ["alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: fast-food-secrets
            - configMapRef:
                name: fast-food-config
      restartPolicy: Never
  backoffLimit: 1
